local M = {}

M.base_30 = {
  white = "#DEE1E6",
  darker_black = "#1C1C1C",
  black = "#1E1E1E",
  black2 = "#252525",
  one_bg = "#2A2A2A",
  one_bg2 = "#333333",
  one_bg3 = "#3E3E3E",
  grey = "#42464e",
  grey_fg = "#A0A0A0",
  grey_fg2 = "#B3B3B3",
  light_grey = "#5E626C",
  red = "#D6626B",
  baby_pink = "#D47D85",
  pink = "#B66ED3",
  line = "#2E2E2E",
  green = "#8AA66C",
  vibrant_green = "#B5CEA8",
  blue = "#4E90C0",
  nord_blue = "#81A1C1",
  yellow = "#D2C89A",
  sun = "#D1A14F",
  purple = "#C586C0",
  dark_purple = "#B38EE0",
  teal = "#47A7AA",
  orange = "#D19A66",
  cyan = "#4EC9B0",
  statusline_bg = "#222222",
  lightbg = "#2A2A2A",
  pmenu_bg = "#62ACE1",
  folder_bg = "#b6bdca",
}

M.base_16 = {
  base00 = "#1E1E1E",
  base01 = "#21262E",
  base02 = "#242931",
  base03 = "#585A5C",
  base04 = "#47B3A8",
  base05 = "#abb2bf",
  base06 = "#b6bdca",
  base07 = "#c8ccd4",
  base08 = "#B0D4E7", -- #B0D4E7 -- #9CDCFE
  base09 = "#B5CEA8",
  base0A = "#B29687",
  base0B = "#CE9178",
  base0C = "#D7BA7D",
  base0D = "#D2C89A",
  base0E = "#C586C0",
  base0F = "#80BDE0",
}

M.polish_hl = {
  treesitter = {
    ["@attribute"] = { fg = M.base_16.base09 },
    ["@attribute.builtin"] = { fg = M.base_16.base04 },
    ["@comment"] = { fg = M.base_16.base03 },
    ["@constant"] = { fg = M.base_30.pmenu_bg },
    ["@constant.builtin"] = { fg = M.base_30.pmenu_bg },
    ["@constructor"] = { fg = M.base_30.cyan },
    ["@function"] = { fg = M.base_30.yellow },
    ["@function.builtin"] = { fg = M.base_16.base09 },
    ["@function.call"] = { fg = M.base_30.yellow },
    ["@function.method.call"] = { fg = M.base_30.yellow },
    ["@keyword"] = { fg = M.base_30.purple },
    ["@keyword.conditional"] = { fg = M.base_30.purple },
    ["@keyword.coroutine"] = { fg = M.base_16.base0D },
    ["@keyword.directive"] = { fg = M.base_30.red },
    ["@keyword.exception"] = { fg = M.base_30.purple },
    ["@keyword.function"] = { fg = M.base_30.blue },
    ["@keyword.import"] = { fg = M.base_16.base0D },
    ["@keyword.operator"] = { fg = M.base_30.blue },
    ["@keyword.return"] = { fg = M.base_16.yellow },
    ["@keyword.type"] = { fg = M.base_30.blue },
    ["@lsp.type.macro"] = { fg = M.base_30.blue },
    ["@operator"] = { fg = M.base_16.base06 },
    ["@punctuation.bracket"] = { fg = M.base_16.base0C },
    ["@punctuation.delimiter"] = { fg = M.base_16.base06 },
    ["@punctuation.special"] = { fg = M.base_16.base07 },
    ["@type"] = { fg = M.base_16.base04 },
    ["@type.builtin"] = { fg = M.base_16.base04 },
    ["@variable"] = { fg = M.base_16.base08 },
    ["@variable.builtin"] = { fg = M.base_16.base08 },
    ["@variable.member.key"] = { fg = M.base_30.vibrant_green },
    ["@variable.parameter"] = { fg = M.base_16.base08 },
  },
}

M.type = "dark"
M = require("base46").override_theme(M, "vscode_custom")

return M
